CREATE TABLE `my_money_log` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MONEY` decimal(6,2) NOT NULL COMMENT '价格',
  `USEFOR` varchar(50) NOT NULL COMMENT '用途',
  `UID` int(11) NOT NULL COMMENT '用户ID',
  `USER_NAME` varchar(50) DEFAULT NULL COMMENT '用户名',
  `CREATE_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `WEEKS` varchar(4) DEFAULT NULL COMMENT '一个月的第几周',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8