CREATE TABLE `user` (
	`ID` int(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NOT NULL COMMENT '姓名',
	`PASSWORD` varchar(200) DEFAULT NULL COMMENT '密码',
	`GANDER` tinyint(4) DEFAULT NULL COMMENT '性别',
	`IS_ADMIN` tinyint(4) DEFAULT NULL COMMENT '是否是管理员',
	`STATUS` tinyint(4) DEFAULT NULL COMMENT '是否正在使用；0：停用；1使用',
	`TEL` int(11) DEFAULT NULL COMMENT '电话',
	`QQ` int(11) DEFAULT NULL COMMENT 'QQ账号',
	`WEIXIN` varchar(200) DEFAULT NULL COMMENT '微信名',
	`EMAIL` varchar(200) DEFAULT NULL COMMENT '邮件',
	`CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	`LAST_LOGIN` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后登录时间',
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
